### ISSUE TITLE
Work stealing IPIs not working

### ISSUE THREAD

**Issue by jackhumphries** [ix-project/zygos#1]
I'm trying to run the work stealing functionality of Zygos. It appears that the while loop in `__xapic_wait_icr_idle` (in inc/ix/apic.h) loops infinitely.

Could you describe your hardware configuration? We suspect that you may have an xAPIC and that we have an x2APIC, which could cause the issue (since x2APICs use MSRs). Maybe we need to reimplement the APIC code using MSRs instead of memory-mapped registers?

**Comment by prekageo** [comment]
It's true that we use xAPIC. Can you try to reboot your machine with the `nox2apic` kernel parameter?

**Comment by jackhumphries** [comment]
Thanks for your help. I tried that and now it seems that I can send IPIs (or at least apic_send_ipi is returning now), but I can't seem to receive IPIs. I tried modifying the no_op IX system call to do the following:

```
static void test_handler(struct dune_tf *tf) {
        printf("Received IPI\n");
        apic_eoi();
}

static void bsys_nop(void)
{       
        dune_register_intr_handler(0xf2, test_handler);
        dune_control_guest_ints(true);
        
        apic_send_ipi(3, 0xf2);
        printf("Sent IPI\n");
}
```

In ix.conf, I have set the IX system to use cpus 0, 1, 2, and 3. When I start the echo server application (which calls the no_op system call), each of the four cores prints "Sent IPI", however no core prints "Received IPI".

I am going to continue to debug the system. Please let me know if you have any tips.

**Comment by jackhumphries** [comment]
Also, I'm trying to understand how the posted IPI functionality works and I was wondering if you could answer a question. It seems that APIC_BASE is a guest virtual address that is being mapped to GPA_APIC_BASE, which is a guest physical address. GPA_APIC_BASE is then mapped to the host physical address of the memory-mapped APIC registers. Based on what I've read in Intel's manual, it seems that there is special functionality for virtualizing reads and writes to the APIC registers, but I'm not sure if you're doing that here. Does giving the Dune process access to the APIC registers the way you have break Dune's safety guarantees or is there some virtualization code that ensures safety? Thanks for your help!

**Comment by prekageo** [comment]
`dune_register_intr_handler` and `dune_control_guest_ints` must be called by all threads before they are able to accept IPIs.
