### ISSUE TITLE
exit due to EPT violation

### ISSUE THREAD

**Issue by Qilewuqiong** [ix-project/zygos#3]
cannot set up ix, the error information is:

dune: exit due to EPT violation, and
ept: failed to get user page GPA 0x4036a00000
vmx: page fault failure GPA 0x4036a0000, GVA: 0x4036a0000

the cpu of my server is E5-2680 v3

**Comment by prekageo** [comment]
Hi,

1. Which commit are you running?
2. Have you made any changes?
3. What is your kernel version?
4. What is the exact command line that you are using?
5. Please copy-paste a 10 line context around the error message.

**Comment by Qilewuqiong** [comment]
Hi George,
1. Actually I am running the "ix" master with the echoserver example.

2. I didn't make any change to "dune" ( actually, I tried to change the value of  GPA_MAP_SIZE 1<<36 to 1<<32, but it didn't work, so  I changed it back).   

3. I am using ubuntu 16.04, the kernel version is 4.4.0-139

4. the context information is :
EAL: PCI device 0000:85:00.1 on NUMA socket 1
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL:   PCI memory mapped at 0x7fcfbbe00000
EAL:   PCI memory mapped at 0x7fcfbbe80000
PMD: eth_ixgbe_dev_init(): MAC: 2, PHY: 18, SFP+: 6
PMD: eth_ixgbe_dev_init(): port 0 vendorID=0x8086 deviceID=0x10fb
21:15:05 <4>: init: module dpdk       SUCESS
21:15:05 <4>: init: module ethdev     SUCESS
CPU 00| 21:15:05 <4>: cpu: started core 0, numa node 0
CPU 00| 21:15:05 <4>: init: module firstcpu   SUCESS
dune: exit due to EPT violation

dmesg information:
[ 4797.552156] ept: GPA: 0x4035e00000, GVA: 0x4035e00000, HVA: 0x4035e00000, flags: 182
[ 4797.552160] ept: failed to get user page 4035e00000
[ 4797.552162] vmx: page fault failure GPA: 0x4035e00000, GVA: 0x4035e00000
[ 4797.552163] vmx: --- Begin VCPU Dump ---
[ 4797.552164] vmx: CPU 0 VPID 1
[ 4797.552166] vmx: RIP 0x000000007000f4b8 RFLAGS 0x00010206
[ 4797.552167] vmx: RAX 0x0000000000000000 RCX 0x0000000035e00000
[ 4797.552168] vmx: RDX 0x0000000000000000 RBX 0x0000004063200000
[ 4797.552170] vmx: RSP 0x00007fff4e230c40 RBP 0xffffffc000000000
[ 4797.552171] vmx: RSI 0x00007fff4e230c00 RDI 0x0000000000000000
[ 4797.552172] vmx: R8  0x0000000072952f40 R9  0x0000000000000000
[ 4797.552174] vmx: R10 0x0000000000000143 R11 0x0000000000000000
[ 4797.552175] vmx: R12 0x0000000000000319 R13 0x0000004000000000
[ 4797.552176] vmx: R14 0x0000004035e00000 R15 0x0000000000000319

**Comment by prekageo** [comment]
Thanks for that. It's useful information. Can you please use objdump or gdb on the ix binary and disassemble around 7000f4b8? Or you can upload the binary somewhere and I can do it.

**Comment by Qilewuqiong** [comment]
yes, the context is:

            7000f495:   48 83 c3 01             add    $0x1,%rbx
     8     7000f499:   48 c1 e3 15             shl    $0x15,%rbx
     7     7000f49d:   48 01 c3                add    %rax,%rbx
     6     7000f4a0:   eb 12                   jmp    7000f4b4 <page_alloc_contig_on_node+0x84>
     5     7000f4a2:   66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)
     4     7000f4a8:   49 81 c6 00 00 20 00    add    $0x200000,%r14
     3     7000f4af:   4c 39 f3                cmp    %r14,%rbx
     2     7000f4b2:   74 64                   je     7000f518 <page_alloc_contig_on_node+0xe8>
     1     7000f4b4:   49 8d 0c 2e             lea    (%r14,%rbp,1),%rcx
**14084      7000f4b8:   41 c7 06 00 00 00 00    movl   $0x0,(%r14)**
     1     7000f4bf:   ba 00 00 20 00          mov    $0x200000,%edx
     2     7000f4c4:   be 01 00 00 00          mov    $0x1,%esi
     3     7000f4c9:   4c 89 f7                mov    %r14,%rdi
     4     7000f4cc:   48 c1 e9 15             shr    $0x15,%rcx
     5     7000f4d0:   48 c1 e1 04             shl    $0x4,%rcx
     6     7000f4d4:   48 81 c1 40 48 3b 70    add    $0x703b4840,%rcx
     7     7000f4db:   e8 f0 f5 ff ff          callq  7000ead0 <mem_lookup_page_machine_addrs>
     8     7000f4e0:   85 c0                   test   %eax,%eax
     9     7000f4e2:   74 c4                   je     7000f4a8 <page_alloc_contig_on_node+0x78>
    10     7000f4e4:   ba 00 00 20 00          mov    $0x200000,%edx
    11     7000f4e9:   44 89 e6                mov    %r12d,%esi
    12     7000f4ec:   4c 89 ef                mov    %r13,%rdi
    13     7000f4ef:   e8 ac f5 ff ff          callq  7000eaa0 <mem_free_pages>

**Comment by prekageo** [comment]
Is this bug similar to this one: https://github.com/ix-project/ix/issues/4? Can you try the workaround for that issue?

**Comment by Qilewuqiong** [comment]
Yes, thanks, George.  They are similar; however, changing the GPA_MAP_SIZE to 1<<32 didn't work for me. I will try to address it with the dune patch you mentioned there.

**Comment by Qilewuqiong** [comment]
The above error may be caused by memory shortage as I only allocated 512*2M hugepages for each socket. When I changed it to 4096, during the setup process, it can successfully finish the syscall init. However, it still crashed by EPT violation as follows:

CPU 00| 23:11:52 <4>: init: module mbuf       SUCESS
mempool_datastore: pbuf            pages:  18 elem_len:  48 nostraddle:0 chunk_size:128 num_chunks:46144 [0x3ffd000000-0x3fff400000]
mempool_datastore: pbuf_payload    pages: 512 elem_len:4096 nostraddle:0 chunk_size:128 num_chunks:42048 [0x3fbd000000-0x3ffd000000]
mempool_datastore: tcp_pcb         pages:  34 elem_len: 272 nostraddle:0 chunk_size:128 num_chunks:42048 [0x3fb8c00000-0x3fbd000000]
mempool_datastore: tcp_seg         pages:   4 elem_len:  32 nostraddle:0 chunk_size:128 num_chunks:42048 [0x3fb8400000-0x3fb8c00000]
CPU 00| 23:11:53 <4>: init: module memp       SUCESS
mempool_datastore: pcb             pages:  16 elem_len:  64 nostraddle:0 chunk_size:128 num_chunks:44096 [0x3fb6400000-0x3fb8400000]
mempool_datastore: ip              pages:   4 elem_len:  16 nostraddle:1 chunk_size:128 num_chunks:44096 [0x4063200000-0x4063a00000]
CPU 00| 23:11:53 <4>: init: module tcpapi     SUCESS
CPU 00| 23:11:53 <4>: init: percpu phase 0
CPU 00| 23:11:53 <4>: init: module timer      on 0: SUCESS
CPU 00| 23:11:53 <4>: init: module mbuf       on 0: SUCESS
CPU 00| 23:11:53 <4>: init: module memp       on 0: SUCESS
CPU 00| 23:11:53 <4>: init: module tcpapi     on 0: SUCESS
CPU 00| 23:11:53 <4>: init: module migration  on 0: SUCESS
CPU 00| 23:11:53 <4>: init: module syscall    on 0: SUCESS
dune: exit due to EPT violation

the context dump is:
[11431.469735] gpa_to_hva: gpa=70010920 clause=0 ret=70010920 x86_phys_bits=2e phys_end=400000000000 GPA_STACK_SIZE=40000000 GPA_MAP_SIZE=fc0000000 mm->mmap_base=7f40b0558000 LG_ALIGN(mm->mmap_base)=7f40c0000000 mm->start_stack=7fff79139150 LG_ALIGN(mm->start_stack)=7fff80000000
[11431.469747] gpa_to_hva: gpa=4063a00000 clause=0 ret=4063a00000 x86_phys_bits=2e phys_end=400000000000 GPA_STACK_SIZE=40000000 GPA_MAP_SIZE=fc0000000 mm->mmap_base=7f40b0558000 LG_ALIGN(mm->mmap_base)=7f40c0000000 mm->start_stack=7fff79139150 LG_ALIGN(mm->start_stack)=7fff80000000
[11431.470232] gpa_to_hva: gpa=703a3ba8 clause=0 ret=703a3ba8 x86_phys_bits=2e phys_end=400000000000 GPA_STACK_SIZE=40000000 GPA_MAP_SIZE=fc0000000 mm->mmap_base=7f40b0558000 LG_ALIGN(mm->mmap_base)=7f40c0000000 mm->start_stack=7fff79139150 LG_ALIGN(mm->start_stack)=7fff80000000
[11431.470240] gpa_to_hva: gpa=0 clause=0 ret=0 x86_phys_bits=2e phys_end=400000000000 GPA_STACK_SIZE=40000000 GPA_MAP_SIZE=fc0000000 mm->mmap_base=7f40b0558000 LG_ALIGN(mm->mmap_base)=7f40c0000000 mm->start_stack=7fff79139150 LG_ALIGN(mm->start_stack)=7fff80000000
[11431.470244] ept: failed to get user page 0
[11431.470245] vmx: page fault failure GPA: 0x0, GVA: 0x0
[11431.470247] vmx: --- Begin VCPU Dump ---
[11431.470247] vmx: CPU 0 VPID 1
[11431.470249] vmx: RIP 0x000000007000a670 RFLAGS 0x00010206
[11431.470250] vmx: RAX 0x0000000000000000 RCX 0x000000007fffffc3
[11431.470251] vmx: RDX 0x0000000000000001 RBX 0x0000003fff400200
[11431.470252] vmx: RSP 0x00007fff79138fc0 RBP 0x0000000000000000
[11431.470253] vmx: RSI 0x0000003fff400740 RDI 0x0000000000000000
[11431.470254] vmx: R8  0x0000000000000000 R9  0x000000000000003c
[11431.470255] vmx: R10 0x000000000000003c R11 0x0000000000000000
[11431.470256] vmx: R12 0x0000003fff400200 R13 0x0000000000000000
[11431.470258] vmx: R14 0x0000000000000000 R15 0x0000000000000000

I am confused why it failed by getting user page 0

**Comment by prekageo** [comment]
null pointer dereference? check with objdump what's around 7000a670.

**Comment by Qilewuqiong** [comment]
Thanks.  I am still trying to figure out where the problem is by referencing the eth_dev_get_rx_queue function of the source code.

000000007000a640 <eth_dev_get_rx_queue>:
    23     7000a640:   ba 01 00 00 00          mov    $0x1,%edx
    22     7000a645:   0f 1f 00                nopl   (%rax)
    21     7000a648:   89 d0                   mov    %edx,%eax
    20     7000a64a:   87 05 fc ff 2d 00       xchg   %eax,0x2dfffc(%rip)        # 702ea64c <eth_dev_lock>
    19     7000a650:   85 c0                   test   %eax,%eax
    18     7000a652:   74 12                   je     7000a666 <eth_dev_get_rx_queue+0x26>
    17     7000a654:   0f 1f 40 00             nopl   0x0(%rax)
    16     7000a658:   8b 05 ee ff 2d 00       mov    0x2dffee(%rip),%eax        # 702ea64c <eth_dev_lock>
    15     7000a65e:   85 c0                   test   %eax,%eax
    14     7000a660:   74 e6                   je     7000a648 <eth_dev_get_rx_queue+0x8>
    13     7000a662:   f3 90                   pause
    12     7000a664:   eb f2                   jmp    7000a658 <eth_dev_get_rx_queue+0x18>
    11     7000a666:   41 55                   push   %r13
    10     7000a668:   41 54                   push   %r12
     9     7000a66a:   55                      push   %rbp
     8     7000a66b:   53                      push   %rbx
     7     7000a66c:   48 83 ec 08             sub    $0x8,%rsp
     6     **7000a670:   48 8b 07                mov    (%rdi),%rax**
     5     7000a673:   44 0f b7 68 18          movzwl 0x18(%rax),%r13d
     4     7000a678:   66 44 39 68 1c          cmp    %r13w,0x1c(%rax)
     3     7000a67d:   0f 86 c4 00 00 00       jbe    7000a747 <eth_dev_get_rx_queue+0x107>

7000a611:   7f dd                   jg     7000a5f0 <eth_dev_stop+0x50>
    25     7000a613:   48 8b 78 08             mov    0x8(%rax),%rdi
    24     7000a617:   31 d2                   xor    %edx,%edx
    23     7000a619:   31 c9                   xor    %ecx,%ecx
    22     7000a61b:   66 89 50 18             mov    %dx,0x18(%rax)
    21     7000a61f:   66 89 48 1a             mov    %cx,0x1a(%rax)
    20     7000a623:   e8 48 8e ff ff          callq  70003470 <free@plt>
    19     7000a628:   48 8b 03                mov    (%rbx),%rax
    18     7000a62b:   5b                      pop    %rbx
    17     7000a62c:   5d                      pop    %rbp
    16     7000a62d:   41 5c                   pop    %r12
    15     7000a62f:   48 8b 38                mov    (%rax),%rdi
    14     7000a632:   e9 39 8e ff ff          jmpq   70003470 <free@plt>
    13     7000a637:   66 0f 1f 84 00 00 00    nopw   0x0(%rax,%rax,1)

**Comment by Qilewuqiong** [comment]
Thanks, Gorge. The problem is addressed. It is caused by the wrong eth_dev in the init_network_cpu function (due to my modification).

**Comment by prekageo** [comment]
Good to know. I was about to write to you to check eth_dev.

**Comment by Qilewuqiong** [comment]
Thank you.
